#!/usr/bin/env bash

set -o errexit
set -o pipefail

function selection {
  cat <<EOF
{
  "driver": "$1",
  "variant": "$2",
  "exit": 0
}
EOF
}

function list() {
  cat <<EOF

{
    "protocol": {
        "version": 0.1
    },
    "operation": {
        "reboot": false
    },
    "drivers": {
        "avago-megaraid-sas": {
            "type": "storage",
            "friendly_name": "avago-megaraid-sas",
            "description": "avago-megaraid-sas",
            "info": "avago-megaraid-sas",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "avago-mpt3sas": {
            "type": "storage",
            "friendly_name": "avago-mpt3sas",
            "description": "avago-mpt3sas",
            "info": "avago-mpt3sas",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "broadcom-bnxt-en": {
            "type": "network",
            "friendly_name": "broadcom-bnxt-en",
            "description": "broadcom-bnxt-en",
            "info": "broadcom-bnxt-en",
            "selected": "generic",
            "active": "generic",
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": true,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "broadcom-mpi3mr": {
            "type": "storage",
            "friendly_name": "broadcom-mpi3mr",
            "description": "broadcom-mpi3mr",
            "info": "broadcom-mpi3mr",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "chelsio-cxgb4": {
            "type": "network",
            "friendly_name": "chelsio-cxgb4",
            "description": "chelsio-cxgb4",
            "info": "chelsio-cxgb4",
            "selected": "oem",
            "active": "oem",
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": true,
                    "priority": 100,
                    "status": "beta"
                },
                "oem": {
                    "version": "1.3",
                    "hardware_present": true,
                    "priority": 80,
                    "status": "beta"
                }
            }
        },
        "cisco-enic": {
            "type": "network",
            "friendly_name": "cisco-enic",
            "description": "cisco-enic",
            "info": "cisco-enic",
            "selected": "generic",
            "active": "dell",
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": true,
                    "priority": 100,
                    "status": "beta"
                },
                "dell": {
                    "version": "1.5",
                    "hardware_present": true,
                    "priority": 90,
                    "status": "beta"
                }
            }
        },
        "cisco-fnic": {
            "type": "network",
            "friendly_name": "cisco-fnic",
            "description": "cisco-fnic",
            "info": "cisco-fnic",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "emulex-lpfc": {
            "type": "network",
            "friendly_name": "emulex-lpfc",
            "description": "emulex-lpfc",
            "info": "emulex-lpfc",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-e1000e": {
            "type": "network",
            "friendly_name": "intel-e1000e",
            "description": "intel-e1000e",
            "info": "intel-e1000e",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-fm10k": {
            "type": "network",
            "friendly_name": "intel-fm10k",
            "description": "intel-fm10k",
            "info": "intel-fm10k",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-i40e": {
            "type": "network",
            "friendly_name": "intel-i40e",
            "description": "intel-i40e",
            "info": "intel-i40e",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-ice": {
            "type": "network",
            "friendly_name": "intel-ice",
            "description": "intel-ice",
            "info": "intel-ice",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-igb": {
            "type": "network",
            "friendly_name": "intel-igb",
            "description": "intel-igb",
            "info": "intel-igb",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-igc": {
            "type": "network",
            "friendly_name": "intel-igc",
            "description": "",
            "info": "",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "intel-ixgbe": {
            "type": "network",
            "friendly_name": "intel-ixgbe",
            "description": "intel-ixgbe",
            "info": "intel-ixgbe",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "mellanox-mlnxen": {
            "type": "network",
            "friendly_name": "mellanox-mlnxen",
            "description": "mellanox-mlnxen",
            "info": "mellanox-mlnxen",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "microsemi-aacraid": {
            "type": "storage",
            "friendly_name": "microsemi-aacrai",
            "description": "microsemi-aacrai",
            "info": "microsemi-aacrai",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "microsemi-smartpqi": {
            "type": "storage",
            "friendly_name": "microsemi-smartpqi",
            "description": "microsemi-smartpqi",
            "info": "microsemi-smartpqi",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "qlogic-fastlinq": {
            "type": "network",
            "friendly_name": "qlogic-fastlinq",
            "description": "qlogic-fastlinq",
            "info": "qlogic-fastlinq",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        },
        "qlogic-netxtreme2": {
            "type": "network",
            "friendly_name": "qlogic-netxtreme2",
            "description": "qlogic-netxtreme2",
            "info": "qlogic-netxtreme2",
            "selected": null,
            "active": null,
            "variants": {
                "generic": {
                    "version": "1.2",
                    "hardware_present": false,
                    "priority": 100,
                    "status": "beta"
                }
            }
        }
    }
}
EOF
}

# Initialize variables with default values
l_flag=false
s_flag=false
n_value=""
v_value=""

# Use getopt to parse command-line options
while getopts "lsn:v:" opt; do
  case "$opt" in
    l)
      l_flag=true
      ;;
    s)
      s_flag=true
      ;;
    n)
      n_value="$OPTARG"
      ;;
    v)
      v_value="$OPTARG"
      ;;
    \?)  # Invalid option
      echo "Invalid option: -$OPTARG" >&2  #>&2 redirects error message to stderr
      exit 1
      ;;
    :)   # Missing argument for option
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Shift the remaining positional parameters (if any)
shift $((OPTIND - 1))

# We don't properly prevent illegal combinations because this is just a
# mock. So we recognise -l first.
if $l_flag; then
  list
  exit 0
fi

if $s_flag; then
  if [ -z "$n_value" ]; then
    echo "missing -n" >&2
    exit 1
  fi
  if [ -z "$v_value" ]; then
    echo "missing -v" >&2
    exit 1
  fi

  selection "$n_value" "$v_value"
  exit 0
fi
