[Unit]
ConditionKernelCommandLine=sshpassword

[Service]
ExecStartPre=/bin/sh -c '/bin/sed -e "s/.*sshpassword=\([^ ]*\).*/root:\1/" /proc/cmdline | /sbin/chpasswd'
ExecStartPre=/bin/sh -c 'echo PermitRootLogin yes >> /etc/ssh/sshd_config'
